spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true



# ===============================
# Uncomment this section for MySQL
# ===============================

#server:
#  port: 8000
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/hotel_db
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: root
#
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
#
#  servlet:
#    multipart:
#      max-file-size: 5MB
#      max-request-size: 5MB
#      file-size-threshold: 2KB
#
#security:
#  jwt:
#    secret-key: 36763979244226452948404D635166546A576D5A7134743777217A25432A462D
#    expire-length: 3600000
